// <auto-generated />
using System;
using AwladRizk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwladRizk.Persistence.Migrations
{
    [DbContext(typeof(AwladRizkDbContext))]
    partial class AwladRizkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AwladRizk.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Admin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@awladrizk.com",
                            FullName = "Admin",
                            PasswordHash = "$2a$12$LJ3m4ys5LlGGMr6VJR8X7OE4J.K3FZkBGDMHgJHGQ3T5jR5Yn2mVe",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍿",
                            NameAr = "شيبسي ومقرمشات",
                            NameEn = "Chips & Snacks",
                            Slug = "chips-snacks",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🧃",
                            NameAr = "عصائر ومشروبات",
                            NameEn = "Juices & Drinks",
                            Slug = "juices-drinks",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "☕",
                            NameAr = "قهوة وشاي",
                            NameEn = "Coffee & Tea",
                            Slug = "coffee-tea",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🧀",
                            NameAr = "ألبان وأجبان",
                            NameEn = "Dairy & Cheese",
                            Slug = "dairy-cheese",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍪",
                            NameAr = "بسكويت وحلويات",
                            NameEn = "Biscuits & Sweets",
                            Slug = "biscuits-sweets",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🥫",
                            NameAr = "معلبات",
                            NameEn = "Canned Food",
                            Slug = "canned-food",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🧹",
                            NameAr = "منظفات",
                            NameEn = "Cleaning",
                            Slug = "cleaning",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍝",
                            NameAr = "معكرونة وأرز",
                            NameEn = "Pasta & Rice",
                            Slug = "pasta-rice",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NewsletterSubscribers", (string)null);
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeText = "30%",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خصم 30% على كل منتجات شيبسي",
                            DescriptionEn = "30% off all Chipsy products",
                            DiscountPercent = 30,
                            Icon = "🔥",
                            IsActive = true,
                            TitleAr = "🔥 خصم 30% على شيبسي الأحجام الكبيرة",
                            TitleEn = "🔥 30% Off Chipsy Large Bags",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BadgeText = "B3G1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "اشترِ 3 جهينة واحصل على 1 مجاناً",
                            DescriptionEn = "Buy 3 Juhayna get 1 free",
                            DiscountPercent = 25,
                            Icon = "🧃",
                            IsActive = true,
                            TitleAr = "🧃 عصير جهينة: اشترِ 3 واحصل على 1 مجاناً",
                            TitleEn = "🧃 Juhayna Juice: Buy 3 Get 1 Free",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BadgeText = "٨٥ ج",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "نسكافيه ٣ في ١ بـ ٨٥ جنيه بدلاً من ١٢٠",
                            DescriptionEn = "Nescafé 3in1 EGP 85 instead of 120",
                            DiscountPercent = 29,
                            Icon = "☕",
                            IsActive = true,
                            TitleAr = "☕ عرض نسكافيه: الكيس الكبير بـ ٨٥ جنيه بدلاً من ١٢٠",
                            TitleEn = "☕ Nescafé Offer: Large Pack EGP 85 Instead of 120",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BadgeText = "20%",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خصم 20% على كل المنظفات",
                            DescriptionEn = "20% off all cleaning products",
                            DiscountPercent = 20,
                            Icon = "🧹",
                            IsActive = true,
                            TitleAr = "🧹 خصم 20% على كل المنظفات",
                            TitleEn = "🧹 20% Off All Cleaning Products",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BadgeText = "٩٥ ج",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شاي العروسة ٢٠٠ كيس بـ ٩٥ جنيه فقط",
                            DescriptionEn = "El Arosa Tea 200 bags for EGP 95 only",
                            DiscountPercent = 24,
                            Icon = "☕",
                            IsActive = true,
                            TitleAr = "☕ شاي العروسة ٢٠٠ كيس بـ ٩٥ جنيه فقط",
                            TitleEn = "☕ El Arosa Tea 200 Bags for EGP 95 Only",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BadgeText = "25%",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فول كاليفورنيا بخصم ٢٥%",
                            DescriptionEn = "California Garden Foul 25% off",
                            DiscountPercent = 25,
                            Icon = "🥫",
                            IsActive = true,
                            TitleAr = "🥫 فول كاليفورنيا بخصم ٢٥%",
                            TitleEn = "🥫 California Garden Foul 25% Off",
                            ValidUntil = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryArea")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryGovernorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryStreet")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsOnSale");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/chipsy-cheese.png",
                            IsOnSale = true,
                            NameAr = "شيبسي كبيرة - بالجبنة",
                            NameEn = "Chipsy Large - Cheese Flavor",
                            OldPrice = 35m,
                            Price = 25m,
                            StockQty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/juhayna-mango.png",
                            IsOnSale = false,
                            NameAr = "عصير جهينة كلاسيك - مانجو",
                            NameEn = "Juhayna Classic Juice - Mango",
                            Price = 18m,
                            StockQty = 200
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/nescafe-3in1.png",
                            IsOnSale = true,
                            NameAr = "نسكافيه ٣ في ١ - ٣٠ كيس",
                            NameEn = "Nescafé 3in1 - 30 Sachets",
                            OldPrice = 120m,
                            Price = 85m,
                            StockQty = 80
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/domty-cheese.png",
                            IsOnSale = false,
                            NameAr = "جبنة دومتي أبيض مثلثات",
                            NameEn = "Domty White Cheese Triangles",
                            Price = 42m,
                            StockQty = 150
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/arosa-tea.png",
                            IsOnSale = true,
                            NameAr = "شاي العروسة - ٢٠٠ كيس",
                            NameEn = "El Arosa Tea - 200 Bags",
                            OldPrice = 125m,
                            Price = 95m,
                            StockQty = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/molto-croissant.png",
                            IsOnSale = false,
                            NameAr = "مولتو كرواسون - ١٢ قطعة",
                            NameEn = "Molto Croissant - 12 Pack",
                            Price = 60m,
                            StockQty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/chipsy-ketchup.png",
                            IsOnSale = false,
                            NameAr = "شيبسي بالكاتشب",
                            NameEn = "Chipsy - Ketchup Flavor",
                            Price = 15m,
                            StockQty = 180
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/beyti-guava.png",
                            IsOnSale = false,
                            NameAr = "عصير بيتي - جوافة",
                            NameEn = "Beyti Juice - Guava",
                            Price = 12m,
                            StockQty = 200
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/california-foul.png",
                            IsOnSale = true,
                            NameAr = "فول كاليفورنيا جاردن",
                            NameEn = "California Garden Foul",
                            OldPrice = 38m,
                            Price = 28m,
                            StockQty = 90
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/gena-tuna.png",
                            IsOnSale = false,
                            NameAr = "تونة جنة",
                            NameEn = "Gena Tuna",
                            Price = 35m,
                            StockQty = 110
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/regina-pasta.png",
                            IsOnSale = false,
                            NameAr = "مكرونة ريجينا - ٥٠٠ جرام",
                            NameEn = "Regina Pasta - 500g",
                            Price = 22m,
                            StockQty = 140
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/persil-detergent.png",
                            IsOnSale = true,
                            NameAr = "برسيل غسيل - ٤ كيلو",
                            NameEn = "Persil Detergent - 4kg",
                            OldPrice = 190m,
                            Price = 155m,
                            StockQty = 50
                        });
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("AwladRizk.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AwladRizk.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AwladRizk.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("AwladRizk.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Product", b =>
                {
                    b.HasOne("AwladRizk.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AwladRizk.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
